name: pos_manager
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  xml: 6.5.0
  cupertino_icons: ^1.0.8
  flutter_native_splash: 2.4.6
  flutter_launcher_icons: 0.14.4
  firebase_core: 3.11.0
  cloud_firestore: 5.6.3
  firebase_crashlytics: 4.3.2
  firebase_messaging: 15.2.2
  firebase_analytics: 11.4.2
  firebase_auth: 5.4.2
  firebase_remote_config: 5.4.0
  firebase_storage: 12.4.2
  flutter_bloc: 9.1.1
  get_it: 8.0.3
  easy_localization: 3.0.7+1
  flutter_screenutil: 5.9.3
  go_router: 15.1.3
  flutter_secure_storage: 9.2.4
  shared_preferences: 2.5.3
  dio: 5.8.0+1
  extended_image: 10.0.1
  image: ^4.1.7
  flutter_svg: 2.1.0
  device_preview: 1.2.0
  crypto: ^3.0.6
  rxdart: ^0.27.7
  url_launcher: ^6.2.4
  package_info_plus: ^8.3.0
  image_picker: ^1.1.2
  connectivity_plus: ^6.0.5
  permission_handler: ^11.3.1
  flutter_easyloading: ^3.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  go_router_builder: 3.0.0
  build_runner: 2.4.15


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/launcher_icon/
    - assets/splash_screen/
    - assets/images/
    - assets/translations/
    - assets/fonts/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic



